# Moderation and Moderated Mediation ----------------------------------------
# These are the author's original PROCESS model specifications. The PROCESS
# source code is not included. Download and activate the official R version
# of PROCESS before running this script.

# Import data ---------------------------------------------------------------

data_path <- file.path("data", "cwbminorcomps.csv")
if (!file.exists(data_path)) {
  stop("Private dataset not included. Expected file: data/cwbminorcomps.csv")
}

cwb_data <- read.csv(data_path, header = TRUE)

# Model 15: competition -> job insecurity -> CWB, moderated by HH ------------

process(
  cwb_data,
  y = "cwbwcyber",
  x = "comp",
  m = "jis",
  w = "hh",
  cov = c("jissaving", "jisinflate", "age", "tenure", "gender"),
  model = 15,
  converge = .00001,
  iterate = 100,
  hc = 5,
  jn = 0,
  effsize = 0,
  stand = 1,
  xmtest = 0,
  normal = 0,
  mdichok = 0,
  contrast = 999,
  modelbt = 0,
  matrices = 0,
  covmy = 0,
  covcoeff = 0,
  boot = 500,
  mc = 0,
  intprobe = 0.1,
  plot = 1,
  total = 0,
  save = 0,
  mcx = 0,
  mcw = 0,
  mcz = 0,
  moments = 0,
  progress = 1,
  bmatrix = -999,
  wmatrix = -999,
  zmatrix = -999,
  wzmatrix = -999,
  cmatrix = -999,
  xcatcode = 999,
  wcatcode = 999,
  zcatcode = 999,
  wmodval = 999,
  zmodval = 999,
  center = 1,
  conf = 95,
  seed = -999,
  decimals = 9.4,
  maxboot = 0,
  modelres = 0,
  bc = 0,
  outscreen = 1,
  activate = 0
)

# Model 15: job insecurity -> competition -> CWB, moderated by HH ------------

process(
  cwb_data,
  y = "cwbwcyber",
  x = "jis",
  m = "comp",
  w = "hh",
  cov = c("jissaving", "age", "tenure", "gender"),
  model = 15,
  converge = .00001,
  iterate = 100,
  hc = 5,
  jn = 0,
  effsize = 0,
  stand = 1,
  xmtest = 0,
  normal = 0,
  mdichok = 0,
  contrast = 999,
  modelbt = 0,
  matrices = 0,
  covmy = 0,
  covcoeff = 0,
  boot = 500,
  mc = 0,
  intprobe = 0.1,
  plot = 1,
  total = 0,
  save = 0,
  mcx = 0,
  mcw = 0,
  mcz = 0,
  moments = 0,
  progress = 1,
  bmatrix = -999,
  wmatrix = -999,
  zmatrix = -999,
  wzmatrix = -999,
  cmatrix = -999,
  xcatcode = 999,
  wcatcode = 999,
  zcatcode = 999,
  wmodval = 999,
  zmodval = 999,
  center = 1,
  conf = 95,
  seed = 123456,
  decimals = 9.4,
  maxboot = 0,
  modelres = 0,
  bc = 0,
  outscreen = 1,
  activate = 0
)

# Model 2: competition, HH, and conscientiousness predicting CWB ------------

process(
  cwb_data,
  y = "cwbwcyber",
  x = "comp",
  w = "hh",
  z = "consc",
  model = 2,
  converge = .00001,
  iterate = 100,
  hc = 5,
  jn = 0,
  effsize = 0,
  stand = 1,
  xmtest = 0,
  normal = 0,
  mdichok = 0,
  contrast = 999,
  modelbt = 0,
  matrices = 0,
  covmy = 0,
  covcoeff = 0,
  boot = 500,
  mc = 0,
  intprobe = 0.1,
  plot = 1,
  total = 0,
  save = 0,
  mcx = 0,
  mcw = 0,
  mcz = 0,
  moments = 0,
  progress = 1,
  bmatrix = -999,
  wmatrix = -999,
  zmatrix = -999,
  wzmatrix = -999,
  cmatrix = -999,
  xcatcode = 999,
  wcatcode = 999,
  zcatcode = 999,
  wmodval = 999,
  zmodval = 999,
  center = 1,
  conf = 95,
  seed = 123456,
  decimals = 9.4,
  maxboot = 0,
  modelres = 0,
  bc = 0,
  outscreen = 1,
  activate = 0
)
